"""Tables, figures and quoted numbers for Section 6 and Appendix C (reporting only).

Reads the result files of a completed production run (all four variants) and, for the
protein-normalization sensitivity, the main variant of the earlier within-cell-CLR run.
Fits nothing. Run on Titan:

    python code/single_cell_v2/report_application.py --run RUN --within-cell RUN0 \
        --folds data/single_cell/folds.json --out DIR
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib
import numpy as np
from scipy import stats

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

LABELS = {
    "sparse_smart": "SMART",
    "initializer_only": "Lasso--SVD initializer",
    "target_rrr": "Target RRR",
    "target_ridge_rrr": "Target ridge RRR",
    "target_ridge": "Target ridge",
    "lasso": "Target Lasso",
    "source_only": "Source fit only",
    "source_subspace_rrr": "Source-subspace RRR",
    "source_subspace_ridge_rrr": "Source-subspace ridge RRR",
    "ridge_to_source": "Ridge toward the source",
    "source_target_mixture": "Source--target mixture",
    "nuclear_contrast": "Nuclear source correction",
    "park": "Park et al.\\ two-stage NR",
}
ORDER = list(LABELS)
COMPETITORS = ORDER[1:]
# Main-text table: SMART, its initializer, and the four strongest competitors.
MAIN_TABLE = ["sparse_smart", "initializer_only", "target_ridge", "ridge_to_source", "nuclear_contrast", "park"]
VARIANTS = {"main": "Main analysis", "rank_minus2": "Rank $\\hat r-2$", "rank_plus2": "Rank $\\hat r+2$",
            "source_ridge": "Ridge source fit"}
PLAIN = {k: v.replace("--", "-").replace("\\ ", " ") for k, v in LABELS.items()}


def load(run, folds, variants):
    results = {}
    for variant in variants:
        for fold in folds["folds"]:
            path = Path(run) / variant / fold["fold"] / "result.json"
            result = json.loads(path.read_text())
            if not result["complete"] or result["mode"] != "production":
                raise ValueError(f"{path} is not a complete production result")
            results[(variant, fold["fold"])] = result
    if len({r["config_sha256"] for r in results.values()}) != 1:
        raise ValueError("results come from more than one protocol")
    return results


def metric(results, variant, folds, method, key="rmse"):
    """Per-fold test metric. Park et al. is fitted in the main variant only: it uses the raw
    source cells and no rank, so its main-variant fit is its fit under every variant."""
    values = []
    for fold in folds["folds"]:
        methods = results[(variant, fold["fold"])]["methods"]
        if method not in methods and method == "park":
            methods = results[("main", fold["fold"])]["methods"]
        record = methods[method]
        if not record.get("success"):
            raise ValueError(f"{method} failed in {variant}/{fold['fold']}")
        values.append(record["test"][key])
    return np.array(values, dtype=float)


def paired(a, b):
    difference = a - b
    half = stats.t.ppf(0.975, len(difference) - 1) * difference.std(ddof=1) / np.sqrt(len(difference))
    return dict(mean=float(difference.mean()), low=float(difference.mean() - half),
                high=float(difference.mean() + half), better=int(np.sum(difference > 0)), n=len(difference))


def place(means, method):
    return 1 + sum(value < means[method] for key, value in means.items() if key != method)


def fmt(x, digits=3):
    return f"{x:.{digits}f}"


def signed(x, digits=3):
    return f"${x:+.{digits}f}$".replace("+", "+").replace("-", "-")


def table_main(results, folds, methods=ORDER):
    sizes = np.array([f["n_test"] for f in folds["folds"]], dtype=float)
    ours = metric(results, "main", folds, "sparse_smart")
    rows, numbers = [], {}
    for method in methods:
        rmse = metric(results, "main", folds, method)
        mse = metric(results, "main", folds, method, "mse")
        pooled = float(np.sqrt(np.sum(sizes * mse) / sizes.sum()))
        numbers[method] = dict(mean_rmse=float(rmse.mean()), pooled_rmse=pooled,
                               r2=float(metric(results, "main", folds, method, "r2").mean()))
        if method == "sparse_smart":
            rows.append(f"{LABELS[method]} & {fmt(rmse.mean())} & {fmt(pooled)} & -- & -- \\\\")
            continue
        p = paired(rmse, ours)  # competitor minus SMART: positive favours SMART
        numbers[method]["vs_sparse_smart"] = p
        rows.append(f"{LABELS[method]} & {fmt(rmse.mean())} & {fmt(pooled)} & "
                    f"{signed(p['mean'])} ({signed(p['low'])}, {signed(p['high'])}) & {p['better']}/{p['n']} \\\\")
    body = "\n".join(rows)
    tex = ("% Generated by code/single_cell_v2/report_application.py -- do not edit by hand.\n"
           "\\begin{tabular}{@{}lcccc@{}}\n\\toprule\n"
           "Method & Mean & Pooled & Difference (95\\% CI) & Donors \\\\\n\\midrule\n"
           f"{body}\n\\bottomrule\n\\end{{tabular}}\n")
    return tex, numbers


def table_sensitivity(results, folds):
    rows, numbers = [], {}
    for variant, label in VARIANTS.items():
        means = {m: float(metric(results, variant, folds, m).mean()) for m in ORDER}
        ours = metric(results, variant, folds, "sparse_smart")
        best = min(COMPETITORS, key=lambda m: means[m])
        park = paired(metric(results, variant, folds, "park"), ours)
        init = paired(metric(results, variant, folds, "initializer_only"), ours)
        numbers[variant] = dict(sparse_smart=means["sparse_smart"], place=place(means, "sparse_smart"),
                                best_competitor=best, best_competitor_rmse=means[best], park=park, initializer=init)
        rows.append(f"{label} & {fmt(means['sparse_smart'])} & {place(means, 'sparse_smart')} & "
                    f"{LABELS[best]} ({fmt(means[best])}) & {signed(park['mean'])} ({park['better']}/8) & "
                    f"{signed(init['mean'])} ({init['better']}/8) \\\\")
    tex = ("% Generated by code/single_cell_v2/report_application.py -- do not edit by hand.\n"
           "\\begin{tabular}{@{}lccccc@{}}\n\\toprule\n"
           "Setting & SMART & Place of 13 & Best competitor & vs Park et al. & vs initializer \\\\\n\\midrule\n"
           + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    return tex, numbers


def table_normalization(final, within, folds):
    across = {m: float(metric(final, "main", folds, m).mean()) for m in ORDER}
    cellwise = {m: float(metric(within, "main", folds, m).mean()) for m in ORDER}
    rows = [f"{LABELS[m]} & {fmt(cellwise[m])} & {place(cellwise, m)} & {fmt(across[m])} & {place(across, m)} \\\\"
            for m in ORDER]
    tex = ("% Generated by code/single_cell_v2/report_application.py -- do not edit by hand.\n"
           "\\begin{tabular}{@{}lcccc@{}}\n\\toprule\n"
           "& \\multicolumn{2}{c}{Within-cell CLR} & \\multicolumn{2}{c}{Across-cell CLR} \\\\\n"
           "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
           "Method & Mean RMSE & Place & Mean RMSE & Place \\\\\n\\midrule\n"
           + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    return tex, dict(within_cell=cellwise, across_cell=across)


def table_donors(results, folds):
    labels = [folds["donor_labels"][str(f["test_donor"])].replace("donor", "") for f in folds["folds"]]
    header = " & ".join(f"D{d}" for d in labels)
    rows = [f"{LABELS[m]} & " + " & ".join(fmt(v) for v in metric(results, "main", folds, m)) + " \\\\"
            for m in ORDER]
    return ("% Generated by code/single_cell_v2/report_application.py -- do not edit by hand.\n"
            f"\\begin{{tabular}}{{@{{}}l{'c' * len(labels)}@{{}}}}\n\\toprule\n"
            f"Method & {header} \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_folds(results, folds):
    labels = folds["donor_labels"]
    rows = []
    for fold in folds["folds"]:
        r = results[("main", fold["fold"])]
        winner = r["methods"]["sparse_smart"].get("record", {})
        kind = "endpoint" if winner.get("selected_method") == "target_rrr" else f"chart, it.\\ {winner.get('selected_iteration')}"
        validation = ", ".join(labels[str(d)].replace("donor", "D") for d in fold["validation_donors"])
        rows.append(f"{labels[str(fold['test_donor'])].replace('donor', 'D')} & {fold['n_test']} & {validation} & "
                    f"{fold['n_validation']} & {fold['n_training']} & {fold['n_source']} & {r['preprocessing']['n_genes']} & "
                    f"{r['preprocessing']['n_proteins']} & {r['ranks']['rank']} & {r['ranks']['rank0']} & {kind} \\\\")
    return ("% Generated by code/single_cell_v2/report_application.py -- do not edit by hand.\n"
            "\\begin{tabular}{@{}lccccccccll@{}}\n\\toprule\n"
            "Test & $n_{\\rm test}$ & Validation donors & $n_{\\rm val}$ & $n$ & $n_0$ & $p$ & $q$ & $r$ & $r_0$ & Selected \\\\\n"
            "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def figure_donors(results, folds, path):
    labels = [folds["donor_labels"][str(f["test_donor"])].replace("donor", "Donor ") for f in folds["folds"]]
    sizes = [f["n_test"] for f in folds["folds"]]
    order = np.argsort(sizes)
    means = {m: float(metric(results, "main", folds, m).mean()) for m in ORDER}
    shown = ["sparse_smart"] + sorted(COMPETITORS, key=lambda m: means[m])[:4]
    styles = [("#1b3c73", "o", "-"), ("#b3452c", "s", "--"), ("#2e7d4f", "^", "-."), ("#8a6d1f", "v", ":"),
              ("#6c6c6c", "D", (0, (3, 1, 1, 1)))]
    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    x = np.arange(len(order))
    for (color, marker, line), method in zip(styles, shown):
        values = metric(results, "main", folds, method)[order]
        ax.plot(x, values, color=color, marker=marker, ls=line, lw=1.6 if method == "sparse_smart" else 1.1,
                ms=6, label=PLAIN[method], zorder=3 if method == "sparse_smart" else 2)
    ax.set_xticks(x)
    ax.set_xticklabels([f"{labels[i]}\n({sizes[i]} cells)" for i in order], fontsize=8)
    ax.set_ylabel("Test RMSE")
    ax.grid(alpha=0.25)
    handles, names = ax.get_legend_handles_labels()
    fig.legend(handles, names, fontsize=8, ncol=3, frameon=False, loc="lower center", bbox_to_anchor=(0.5, 0.0))
    fig.tight_layout(rect=(0, 0.1, 1, 1))
    fig.savefig(path)
    plt.close(fig)
    return shown


def figure_diagnostics(results, folds, path):
    labels = [folds["donor_labels"][str(f["test_donor"])].replace("donor", "D") for f in folds["folds"]]
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.0), sharey=True)
    summary = {}
    for ax, side, title in ((axes[0], "right", "Protein side"), (axes[1], "left", "Gene side")):
        observed, random, floor = [], [], []
        for fold in folds["folds"]:
            c = results[("main", fold["fold"])]["diagnostics"]["containment"]
            observed.append(np.mean(c[f"{side}_cosines"]))
            random.append(np.mean(c[f"random_{side}"]["mean"]))
            floor.append(np.mean(c["half_split_floor"][side]))
        x = np.arange(len(labels))
        ax.plot(x, observed, "o", color="#1b3c73", label="ILC1 vs NK source")
        ax.plot(x, floor, "x", color="#b3452c", ms=7, label="ILC1 half vs half")
        ax.plot(x, random, "s", mfc="none", color="#6c6c6c", label="ILC1 vs random")
        ax.set_xticks(x)
        ax.set_xticklabels(labels, fontsize=8)
        ax.set_title(title, fontsize=10)
        ax.set_ylim(0, 1)
        ax.grid(alpha=0.25)
        summary[side] = dict(observed=[float(v) for v in observed], random=[float(v) for v in random],
                             half_split=[float(v) for v in floor])
    axes[0].set_ylabel("Mean cosine of principal angles")
    axes[0].legend(fontsize=7.5, frameon=False, loc="lower left")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return summary


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--run", required=True, type=Path)
    parser.add_argument("--within-cell", required=True, type=Path)
    parser.add_argument("--folds", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()
    folds = json.loads(args.folds.read_text())
    final = load(args.run, folds, VARIANTS)
    within = load(args.within_cell, folds, ["main"])
    args.out.mkdir(parents=True, exist_ok=True)
    main_tex, main_numbers = table_main(final, folds)
    short_tex, _ = table_main(final, folds, MAIN_TABLE)
    sensitivity_tex, sensitivity_numbers = table_sensitivity(final, folds)
    normalization_tex, normalization_numbers = table_normalization(final, within, folds)
    (args.out / "tab_application_main.tex").write_text(short_tex)
    (args.out / "tab_application_all.tex").write_text(main_tex)
    (args.out / "tab_application_sensitivity.tex").write_text(sensitivity_tex)
    (args.out / "tab_application_normalization.tex").write_text(normalization_tex)
    (args.out / "tab_application_donors.tex").write_text(table_donors(final, folds))
    (args.out / "tab_application_folds.tex").write_text(table_folds(final, folds))
    shown = figure_donors(final, folds, args.out / "fig_application_donors.pdf")
    diagnostics = figure_diagnostics(final, folds, args.out / "fig_application_diagnostics.pdf")
    selection = [dict(fold=f["fold"], **{k: final[("main", f["fold"])]["methods"]["sparse_smart"].get("record", {}).get(k)
                                        for k in ("selected_method", "selected_iteration", "candidate_index")})
                 for f in folds["folds"]]
    low_rank = [dict(fold=f["fold"], target_rsc=final[("main", f["fold"])]["diagnostics"]["low_rank"]["target_rsc"]["rank"],
                     source_rsc=final[("main", f["fold"])]["diagnostics"]["low_rank"]["source_rsc"]["rank"],
                     rank=final[("main", f["fold"])]["ranks"]["rank"], rank0=final[("main", f["fold"])]["ranks"]["rank0"])
                for f in folds["folds"]]
    alignment = [dict(fold=f["fold"], **{side: final[("main", f["fold"])]["diagnostics"]["alignment"][side]
                                          for side in ("left", "right")}) for f in folds["folds"]]
    numbers = dict(config_sha256=next(iter(final.values()))["config_sha256"], main=main_numbers,
                   sensitivity=sensitivity_numbers, normalization=normalization_numbers,
                   figure_methods=shown, diagnostics=diagnostics, selection=selection, low_rank=low_rank,
                   alignment=alignment)
    (args.out / "application_numbers.json").write_text(json.dumps(numbers, indent=1) + "\n")
    print(json.dumps({k: v for k, v in numbers.items() if k in ("config_sha256", "figure_methods")}, indent=1))
    print(main_tex)
    print(sensitivity_tex)


if __name__ == "__main__":
    main()
