"""Audit paired SparseSMART iteration budgets without fitting an estimator.

The default comparison has 45 cells: three models, source ranks 5 and 7, and
source noise .5, each on five original seeds.  Only the iteration budget may
change.  Training/validation observations and coefficient-error metrics are
independently regenerated by the existing external-grid validator.
"""
from __future__ import annotations

import argparse
from collections import Counter
from copy import deepcopy
from dataclasses import asdict
import hashlib
import json
import math
from pathlib import Path

import numpy as np

import external_validation_data
import run_sparse_smart_external as runner
from run_restricted_rrr import DEFAULT_SEED_FILE, experiment_settings, load_experiment_seeds
from run_sparse_smart import _atomic_json_dump, _digest_json, _json_value
from summarize_sparse_smart import _stats
from summarize_sparse_smart_external_grid import validate_record
from summarize_sparse_smart_tuned import _finite, _integer, _require

HERE = Path(__file__).resolve().parent
DEFAULT_BASE_ROOT = HERE / "result" / "sparse_smart_v03_pilot_500"
DEFAULT_EXTENDED_ROOT = HERE / "result" / "sparse_smart_v03_pilot_2000"
DIFFICULT_SETTINGS = ((2, "rs=5"), (2, "rs=7"), (3, "sigma0=0.5"))


def _without_iterations(configuration):
    value = deepcopy(configuration)
    del value["runner"]["iterations"]
    return value


def _validate_iteration_semantics(record, budget):
    """Check this pilot's solver contract, including unsuccessful candidates."""
    config = record["configuration"]["runner"]
    _require(config["iterations"] == budget, "Wrong iteration budget for this cohort")
    _require(config["initialization_spectrum"] == "projected"
             and config["refinement_solver"] == "anchor_projected",
             "Iteration pilot requires projected initialization and anchor-projected refinement")
    _require(config["init_penalties"] == [.03]
             and config["penalties_u"] == [.0025, .01, .04]
             and config["penalties_v"] == [.0025, .01, .04]
             and config["support_limits"] is None,
             "Iteration pilot requires the prescribed nine-candidate full-support grid")
    _require(config["stationarity_tol"] is not None,
             "Iteration comparison requires an explicit stationarity tolerance")
    for candidate in record["selection_history"]:
        history = candidate["validation_history"]
        if history:
            _require([row["iteration"] for row in history] == list(range(candidate["n_iter"] + 1)),
                     "Incomplete candidate validation trajectory")
            losses = [_finite(row["loss"], "candidate validation loss") for row in history]
            if candidate["selected_iteration"] is not None:
                _require(candidate["selected_iteration"] == min(range(len(losses)), key=losses.__getitem__),
                         "Partial or successful candidate did not retain earliest validation minimum")
        if not candidate["success"]:
            _require(candidate["validation_mse"] is None, "Failed partial candidate was made eligible")
            if candidate.get("partial_validation_mse") is not None:
                _finite(candidate["partial_validation_mse"], "partial validation MSE")
            continue
        diagnostics = candidate["diagnostics"]
        _require(diagnostics["refinement_solver"] == "anchor_projected"
                 and diagnostics["stationarity_scope"] == "full_chart_constraints"
                 and diagnostics["diagnostic_coordinates"] == "omega,d,H",
                 "Successful candidate uses a different solver or stationarity diagnostic")
        if diagnostics["last_projected_gradient_norm"] is not None:
            _finite(diagnostics["last_projected_gradient_norm"], "terminal constrained residual")
        converged = candidate["termination_reason"] == "stationarity"
        _require(diagnostics["optimization_converged"] is converged,
                 "Candidate convergence flag disagrees with termination")
        _require(diagnostics["selected_converged"] ==
                 (converged and candidate["selected_iteration"] == candidate["n_iter"]),
                 "Selected-iterate convergence flag is inconsistent")
        if converged:
            _require(candidate["status"] == "converged", "Stationarity termination has wrong candidate status")
            _require(_finite(diagnostics["last_projected_gradient_norm"], "terminal constrained residual")
                     <= config["stationarity_tol"], "Converged candidate misses stationarity tolerance")
        else:
            _require(candidate["status"] == "completed" and candidate["termination_reason"] == "max_iterations"
                     and candidate["n_iter"] == budget, "Completed candidate did not reach its budget")
    if record["success"]:
        winner = min((c for c in record["selection_history"] if c["success"]),key=lambda c:c["validation_mse"])
        _require(record["termination_reason"] == winner["termination_reason"],
                 "Selected model termination differs from the winning candidate")
        for key in ("optimization_converged","selected_converged","refinement_solver",
                    "stationarity_scope","diagnostic_coordinates","last_projected_gradient_norm"):
            _require(record["diagnostics"][key] == winner["diagnostics"][key],
                     f"Selected model diagnostic differs from the winning candidate: {key}")
        _require(record["diagnostics"]["selected_converged"] ==
                 (record["diagnostics"]["optimization_converged"]
                  and record["selected_iteration"] == record["n_iter"]),
                 "Selected model convergence flag is inconsistent")


def _candidate_prefix(base, extended, base_budget):
    _require(base["candidate_id"] == extended["candidate_id"] and base["params"] == extended["params"],
             "Paired candidate parameters differ")
    history = base["validation_history"]
    longer = extended["validation_history"]
    _require(len(longer) >= len(history) and longer[:len(history)] == history,
             f"Candidate {base['candidate_id']} validation prefix differs")
    # With identical inputs, code, and stopping tolerance, changing only the
    # budget cannot change a stop that happened before that budget was reached.
    stopped = base["termination_reason"] != "max_iterations"
    if stopped:
        for key in ("n_iter", "success", "status", "termination_reason"):
            _require(base[key] == extended[key], f"Early candidate stop did not reproduce: {key}")
        _require(history == longer, "Early-stopped candidate unexpectedly continued")
        kind = "early_convergence_reproduced" if base["termination_reason"] == "stationarity" else "failure_reproduced"
    else:
        _require(base["n_iter"] == base_budget and extended["n_iter"] >= base_budget,
                 "Continuation does not reach the shorter budget")
        kind = "continued" if extended["n_iter"] > base_budget else "failed_at_continuation"
    return dict(candidate_id=base["candidate_id"], kind=kind,
        compared_validation_rows=len(history), base_n_iter=base["n_iter"], extended_n_iter=extended["n_iter"],
        base_success=base["success"], extended_success=extended["success"],
        eligibility_lost=base["success"] and not extended["success"])


def validate_pair(base, extended, *, base_budget=500, extended_budget=2000):
    """Audit a pair after each constituent passes the external-grid validator."""
    for key in ("model", "experiment", "setting", "rd_seed_id", "random_seed", "generator_arguments",
                "training_observed_input_fingerprint", "validation_observed_input_fingerprint",
                "evaluation_truth_fingerprint", "input_fingerprint", "implementation_fingerprint",
                "validation_seed_metadata", "n_train", "n_validation"):
        _require(base[key] == extended[key], f"Paired {key} differs")
    _require(_without_iterations(base["configuration"]) == _without_iterations(extended["configuration"]),
             "Paired configurations differ beyond iteration budget")
    _require(base["configuration"]["runner"]["iterations"] == base_budget
             and extended["configuration"]["runner"]["iterations"] == extended_budget,
             "Pair has incorrect iteration budgets")
    old = {row["candidate_id"]:row for row in base["selection_history"]}
    new = {row["candidate_id"]:row for row in extended["selection_history"]}
    prefixes = [_candidate_prefix(old[i], new[i], base_budget) for i in sorted(old.keys() & new.keys())]
    lost = [row["candidate_id"] for row in prefixes if row["eligibility_lost"]]
    winner_retained, winner_id = None, None
    if base["success"]:
        winner = min((c for c in old.values() if c["success"]), key=lambda c:c["validation_mse"])
        winner_id = winner["candidate_id"]
        winner_retained = winner_id in new and new[winner_id]["success"]
        if winner_retained:
            _require(extended["success"] and extended["validation_loss"] <= base["validation_loss"] + 1e-12,
                     "Validation worsened despite retaining the shorter-run winner and its prefix")
    both = base["success"] and extended["success"]
    coefficient_change = None
    if both:
        a, b = np.asarray(base["C_hat"]), np.asarray(extended["C_hat"])
        coefficient_change = float(np.linalg.norm(a-b) / np.sqrt(a.size))
        if base["best_params"] == extended["best_params"] and base["selected_iteration"] == extended["selected_iteration"]:
            _require(np.array_equal(a,b), "Same candidate and selected iteration produced different coefficients")
    return dict(model=base["model"], experiment=base["experiment"], setting=base["setting"]["suffix"],
        seed_id=base["rd_seed_id"], base_status=base["status"], extended_status=extended["status"],
        both_successful=both, candidate_prefixes=prefixes, eligibility_lost_candidates=lost,
        candidate_ids_missing_base=sorted(new.keys()-old.keys()),
        candidate_ids_missing_extended=sorted(old.keys()-new.keys()),
        full_candidate_searches=len(old)==9 and len(new)==9,
        base_winner_candidate_id=winner_id,
        base_winner_extended_status=new[winner_id]["status"] if winner_id in new else None,
        base_winner_eligible_in_extended=winner_retained,
        base_error=base["avg_err"], extended_error=extended["avg_err"],
        base_validation=base["validation_loss"], extended_validation=extended["validation_loss"],
        error_change=extended["avg_err"]-base["avg_err"] if both else None,
        validation_change=extended["validation_loss"]-base["validation_loss"] if both else None,
        coefficient_change=coefficient_change,
        base_n_iter=base["n_iter"], extended_n_iter=extended["n_iter"],
        base_terminal_residual=base["diagnostics"].get("last_projected_gradient_norm") if base["success"] else None,
        extended_terminal_residual=extended["diagnostics"].get("last_projected_gradient_norm") if extended["success"] else None,
        base_optimizer_converged=base["diagnostics"].get("optimization_converged") if base["success"] else False,
        extended_optimizer_converged=extended["diagnostics"].get("optimization_converged") if extended["success"] else False,
        base_selected_iteration=base["selected_iteration"], extended_selected_iteration=extended["selected_iteration"],
        selected_after_base_budget=bool(both and extended["selected_iteration"] > base_budget),
        selected_parameters_changed=bool(both and base["best_params"] != extended["best_params"]),
        base_configuration_fingerprint=base["configuration_fingerprint"],
        extended_configuration_fingerprint=extended["configuration_fingerprint"],
        normalized_configuration_fingerprint=_digest_json(_without_iterations(base["configuration"])),
        input_fingerprint=base["input_fingerprint"], implementation_fingerprint=base["implementation_fingerprint"])


def _cohort_counts(records):
    successful = [r for r in records if r["success"]]
    candidates = [c for r in records for c in r["selection_history"]]
    return dict(recorded=len(records), successful=len(successful),
        status_counts=dict(Counter(r["status"] for r in records)),
        termination_counts=dict(Counter(r["termination_reason"] or r["failure_reason"] or r["status"] for r in records)),
        candidate_status_counts=dict(Counter(c["status"] for c in candidates)),
        candidate_termination_counts=dict(Counter(c["termination_reason"] or c["status"] for c in candidates)),
        candidate_failures=sum(not c["success"] for c in candidates),
        unavailable_terminal_residual=sum(r["diagnostics"].get("last_projected_gradient_norm") is None for r in successful),
        optimization_converged=sum(r["diagnostics"]["optimization_converged"] for r in successful),
        selected_converged=sum(r["diagnostics"]["selected_converged"] for r in successful),
        selected_initializer=sum(r["selected_iteration"]==0 for r in successful))


def _validate_selected_prediction(record, setting, random_seed, config, cache, generator):
    """Recompute the selected prediction score, not just the saved minimum."""
    if not record["success"]:
        return False
    key=(setting.n,setting.p,setting.q,setting.sigma0,int(random_seed),
         config.n_validation,config.validation_seed_tag)
    if key not in cache:
        generated=external_validation_data.generate_external_validation(
            n_train=setting.n,p=setting.p,q=setting.q,sigma0=setting.sigma0,
            random_seed=int(random_seed),n_validation=config.n_validation,sigma=.5,
            r_star=5,r0_star=10,seed_tag=config.validation_seed_tag,generate_data_fn=generator)
        fingerprint=runner.old_runner._array_fingerprint(generated,("X_validation","Y_validation"))
        cache[key]=(generated["X_validation"],generated["Y_validation"],fingerprint)
    X,Y,fingerprint=cache[key]
    _require(fingerprint==record["validation_observed_input_fingerprint"],
             "Replayed validation inputs disagree with the recorded fingerprint")
    coefficient=np.asarray(record["C_hat"])
    actual=float(np.mean((Y-X@coefficient)**2))
    _require(math.isfinite(actual) and math.isclose(actual,record["validation_loss"],rel_tol=1e-10,abs_tol=1e-12),
             "Selected validation MSE disagrees with saved coefficient predictions")
    return True


def summarize(base_root=DEFAULT_BASE_ROOT, extended_root=DEFAULT_EXTENDED_ROOT, *,
              model_ids=(0,1,2), seed_ids=(0,1,2,3,4), seed_file=DEFAULT_SEED_FILE,
              base_budget=500, extended_budget=2000, generate_data_fn=None):
    """Return per-setting paired aggregates and a reproducibility audit.

    Missing and unsuccessful cells are explicit.  Means and standard errors in
    the paired table use the same jointly successful seed set at both budgets;
    a one-observation standard error is unavailable, never reported as zero.
    """
    model_ids, seed_ids = tuple(model_ids), tuple(seed_ids)
    for values, count, label in ((model_ids,3,"model IDs"),(seed_ids,100,"seed IDs")):
        _require(values and len(set(values))==len(values)
                 and all(type(v) is int and 0<=v<count for v in values), f"Invalid {label}")
    _integer(base_budget, "base budget")
    _integer(extended_budget, "extended budget")
    _require(0 < base_budget < extended_budget, "Iteration budgets must increase and be positive")
    seeds = load_experiment_seeds(seed_file)
    _require(max(seed_ids)<len(seeds), "Requested seed is unavailable")
    roots = {"base":Path(base_root), "extended":Path(extended_root)}
    budgets = {"base":base_budget, "extended":extended_budget}
    records, paths, cache, implementations, configs = {}, [], {}, set(), set()
    prediction_cache, verified_prediction_scores = {}, 0
    generator = generate_data_fn
    groups = []
    for model_id in model_ids:
        for exp_id, suffix in DIFFICULT_SETTINGS:
            setting = next(s for s in experiment_settings(model_id, exp_id) if s.suffix==suffix)
            groups.append((model_id,exp_id,setting))
            for seed_id in seed_ids:
                for cohort,root in roots.items():
                    path = runner.result_path(root, model=f"model{model_id+1}", experiment=f"exp{exp_id+1}",
                                              setting=setting, seed_id=seed_id)
                    if not path.exists():
                        continue
                    try:
                        raw = path.read_bytes()
                        record = json.loads(raw)
                        if generator is None:
                            generator = runner.old_runner._load_generator()
                        config = validate_record(record,path,setting=setting,model_id=model_id,exp_id=exp_id,
                            seed_id=seed_id,random_seed=seeds[seed_id],data_cache=cache,generate_data_fn=generator)
                        _validate_iteration_semantics(record, budgets[cohort])
                        verified_prediction_scores += _validate_selected_prediction(
                            record,setting,seeds[seed_id],config,prediction_cache,generator)
                        normalized = asdict(config)
                        del normalized["iterations"]
                        configs.add(json.dumps(_json_value(normalized),sort_keys=True))
                        implementations.add(record["implementation_fingerprint"])
                        key = (cohort,model_id,exp_id,suffix,seed_id)
                        records[key] = record
                        paths.append(dict(cohort=cohort,path=str(path.resolve()),sha256=hashlib.sha256(raw).hexdigest(),
                            model=record["model"],experiment=record["experiment"],setting=suffix,seed_id=seed_id))
                    except (KeyError,TypeError,ValueError,OverflowError) as error:
                        raise ValueError(f"Invalid iteration-pilot result {path}: {error}") from error
    _require(len(implementations)<=1, "Cannot compare mixed implementation fingerprints")
    _require(len(configs)<=1, "Cannot compare mixed configurations beyond iteration budget")
    pairs, rows = [], []
    for model_id,exp_id,setting in groups:
        group_records = {cohort:[records[(cohort,model_id,exp_id,setting.suffix,s)] for s in seed_ids
            if (cohort,model_id,exp_id,setting.suffix,s) in records] for cohort in roots}
        group_pairs = []
        for seed_id in seed_ids:
            old = records.get(("base",model_id,exp_id,setting.suffix,seed_id))
            new = records.get(("extended",model_id,exp_id,setting.suffix,seed_id))
            if old is not None and new is not None:
                try:
                    group_pairs.append(validate_pair(old,new,base_budget=base_budget,extended_budget=extended_budget))
                except (KeyError,TypeError,ValueError) as error:
                    raise ValueError(f"Invalid pair model{model_id+1} exp{exp_id+1} {setting.suffix} seed{seed_id}: {error}") from error
        pairs.extend(group_pairs)
        paired = [p for p in group_pairs if p["both_successful"]]
        base_counts, extended_counts = (_cohort_counts(group_records[c]) for c in ("base","extended"))
        row = dict(model=f"model{model_id+1}",experiment=f"exp{exp_id+1}",setting=setting.suffix,
            n_train=setting.n,n_validation=100,expected_pairs=len(seed_ids),paired_records=len(group_pairs),
            successful_pairs=len(paired),missing_base=len(seed_ids)-len(group_records["base"]),
            missing_extended=len(seed_ids)-len(group_records["extended"]),
            base_counts=base_counts,extended_counts=extended_counts,
            paired_success_seed_ids=[p["seed_id"] for p in paired],
            mean_is_conditional_on_joint_success=any(not p["both_successful"] for p in group_pairs),
            selected_after_base_budget=sum(p["selected_after_base_budget"] for p in paired),
            selected_after_base_fraction=sum(p["selected_after_base_budget"] for p in paired)/len(paired) if paired else None,
            changed_selected_parameters=sum(p["selected_parameters_changed"] for p in paired),
            pairs_losing_eligible_candidates=sum(bool(p["eligibility_lost_candidates"]) for p in group_pairs),
            validation_improved=sum(p["validation_change"] < -1e-12 for p in paired),
            validation_worsened=sum(p["validation_change"] > 1e-12 for p in paired),
            validation_unchanged=sum(abs(p["validation_change"]) <= 1e-12 for p in paired))
        for field in ("base_error","extended_error","error_change","base_validation","extended_validation",
                      "validation_change","coefficient_change","base_terminal_residual","extended_terminal_residual"):
            values = [p[field] for p in paired if p[field] is not None]
            row[f"{field}_mean"],row[f"{field}_se"] = _stats(values)
            row[f"{field}_count"] = len(values)
        rows.append(row)
    cohort_all = {c:[r for key,r in records.items() if key[0]==c] for c in roots}
    candidate_failures = [dict(cohort=cohort,budget=budgets[cohort],model=record["model"],
        experiment=record["experiment"],setting=suffix,seed_id=seed_id,
        candidate_id=candidate["candidate_id"],status=candidate["status"],n_iter=candidate["n_iter"],
        termination_reason=candidate["termination_reason"],
        terminal_residual=candidate.get("diagnostics",{}).get("last_projected_gradient_norm"),
        selected_partial_iteration=candidate["selected_iteration"],
        partial_validation_mse=candidate.get("partial_validation_mse"))
        for (cohort,_,_,suffix,seed_id),record in sorted(records.items())
        for candidate in record["selection_history"] if not candidate["success"]]
    expected = len(groups)*len(seed_ids)
    audit = dict(schema_version=1,base_root=str(roots["base"].resolve()),extended_root=str(roots["extended"].resolve()),
        base_budget=base_budget,extended_budget=extended_budget,model_ids=list(model_ids),seed_ids=list(seed_ids),
        expected_pairs=expected,paired_records=len(pairs),successful_pairs=sum(p["both_successful"] for p in pairs),
        missing_base=expected-len(cohort_all["base"]),missing_extended=expected-len(cohort_all["extended"]),
        all_expected_records_present=all(len(cohort_all[c])==expected for c in roots),
        cohort_counts={c:_cohort_counts(cohort_all[c]) for c in roots},
        candidate_failures=candidate_failures,
        implementation_fingerprints=sorted(implementations),
        common_runner_config=json.loads(next(iter(configs))) if configs else None,
        regenerated_unique_datasets=len(cache),verified_input_records=len(records),
        independently_recomputed_validation_scores=verified_prediction_scores,
        validation_prediction_datasets=len(prediction_cache),
        prefix_classifications=dict(Counter(c["kind"] for p in pairs for c in p["candidate_prefixes"])),
        compared_candidate_prefixes=sum(len(p["candidate_prefixes"]) for p in pairs),
        pairs_losing_eligible_candidates=sum(bool(p["eligibility_lost_candidates"]) for p in pairs),
        pairs_losing_base_winner=sum(p["base_winner_eligible_in_extended"] is False for p in pairs),
        pairs=pairs,rows=rows,result_files=paths,
        selection_policy="Candidates and iterates are selected only by validation MSE among successful fits; coefficient truth errors are descriptive, never used to choose the iteration budget.",
        interpretation="Iteration-limit completion is not convergence. Assess an iteration budget using validation improvement, coefficient stability, and constrained stationarity diagnostics.",
        data_protocol="All original training rows plus100 independent validation rows; same data at both budgets; no refit and no other estimator fits.",
        means="Paired mean and sample standard error use only seeds successful at both budgets; a single seed has no estimable standard error.",
        diagnostic_limit="Saved constrained residuals combine proximal displacement and inner-solve uncertainty; these components are not separately recorded.")
    return rows,audit


def _number(value, digits=6):
    return "—" if value is None else f"{value:.{digits}f}"


def _mean_se(row, field):
    return f"{_number(row[field+'_mean'])} ± {_number(row[field+'_se'])}"


def write_outputs(rows, audit, output_root):
    output = Path(output_root)
    output.mkdir(parents=True,exist_ok=True)
    _atomic_json_dump(audit,output/"audit.json")
    short,long = audit["base_budget"],audit["extended_budget"]
    lines = [f"# SparseSMART iteration check: {short} versus {long} updates", "",
        f"Audited {audit['paired_records']}/{audit['expected_pairs']} expected pairs; "
        f"{audit['successful_pairs']} pairs succeeded at both budgets. "
        f"Missing records: {audit['missing_base']} at {short}, {audit['missing_extended']} at {long}.", "",
        "Only the iteration budget changes. Each fit uses all original training rows and the same 100 independent "
        "validation rows, with the same nine-candidate penalty grid, fixed anchors and support semantics, and no refit. "
        "Model I/II/III use 200/300/500 training rows for these settings. No competing method is fitted.", "",
        "Choose the iteration budget using validation improvement, coefficient stability, and optimization diagnostics. "
        "The coefficient errors below use simulation truth only for descriptive evaluation; they do not select candidates, "
        "iterates, or a preferred budget. Reusing validation for many budget choices would require fresh confirmation data.", "",
        "## Candidate failures and selection", "",
        f"Failed candidates: **{audit['cohort_counts']['base']['candidate_failures']} at {short}; "
        f"{audit['cohort_counts']['extended']['candidate_failures']} at {long}**. "
        "These counts concern individual grid candidates; a cell can still succeed by selecting another successful candidate. "
        "Failed partial fits remain ineligible even when their partial validation MSE is lower.", ""]
    if audit["candidate_failures"]:
        lines += ["| Cohort (budget) | Model | Setting | Seed | Candidate | Status | n_iter | Terminal residual |",
                  "|---|---|---|---:|---:|---|---:|---:|"]
        for failure in audit["candidate_failures"]:
            residual = failure["terminal_residual"]
            residual_text = "—" if residual is None else f"{residual:.6g}"
            lines.append(f"| {failure['cohort']} ({failure['budget']}) | {failure['model']} | "
                f"{failure['setting']} | {failure['seed_id']} | {failure['candidate_id']} | "
                f"{failure['status']} | {failure['n_iter']} | {residual_text} |")
        lines += ["", audit["diagnostic_limit"] + " A numerical-stagnation failure is not a stationarity certificate.", ""]
    else:
        lines += ["No candidate failures occurred in the available records.", ""]
    lost_winners = [p for p in audit["pairs"] if p["base_winner_eligible_in_extended"] is False]
    if lost_winners:
        lines += [f"**The {short}-update winner lost eligibility in {len(lost_winners)} paired cell(s).** "
            "When this happens, the longer run can have a worse selected validation MSE: selection excludes the failed "
            "continuation and chooses among the remaining successful candidates. "
            "The shorter run's completed fit is not automatically retained as a fallback.", "",
            f"| Model | Setting | Seed | Winner at {short} | Its status at {long} | Validation {short} | Validation {long} | Change |",
            "|---|---|---:|---:|---|---:|---:|---:|"]
        for pair in lost_winners:
            lines.append(f"| {pair['model']} | {pair['setting']} | {pair['seed_id']} | "
                f"{pair['base_winner_candidate_id']} | {pair['base_winner_extended_status'] or 'missing'} | "
                f"{_number(pair['base_validation'])} | {_number(pair['extended_validation'])} | "
                f"{_number(pair['validation_change'])} |")
        lines.append("")
    lines += ["## Paired outcomes", "",
        "Means and sample standard errors use the same seeds successful at both budgets. Failed partial fits are excluded. "
        "When failures occur these means are conditional on joint success; a single successful pair has no estimable SE. "
        "Missing cells remain visible and are never counted as zero error.", "",
        f"| Model | Setting | Successful pairs | Error {short}, mean ± SE | Error {long}, mean ± SE | "
        f"Validation change ({long}−{short}) | Selected after {short} | Coefficient change |",
        "|---|---|---:|---:|---:|---:|---:|---:|"]
    for row in rows:
        lines.append(f"| {row['model']} | {row['setting']} | {row['successful_pairs']}/{row['expected_pairs']} | "
            f"{_mean_se(row,'base_error')} | {_mean_se(row,'extended_error')} | "
            f"{_number(row['validation_change_mean'])} | {row['selected_after_base_budget']}/{row['successful_pairs']} | "
            f"{_number(row['coefficient_change_mean'])} |")
    lines += ["", "Negative validation change means lower held-out MSE. Coefficient change is "
        "‖Ĉ(long)−Ĉ(short)‖F/√(pq), which measures stability without using truth. "
        "Selecting after the shorter budget indicates that its best validation iterate had not yet been reached.", "",
        "Validation outcomes below count jointly successful pairs; absolute changes at most 1e-12 are treated as unchanged.", "",
        "| Model | Setting | Improved | Unchanged | Worsened |",
        "|---|---|---:|---:|---:|"]
    for row in rows:
        lines.append(f"| {row['model']} | {row['setting']} | {row['validation_improved']} | "
            f"{row['validation_unchanged']} | {row['validation_worsened']} |")
    lines += ["",
        "## Completion and stationarity", "",
        "Iteration-limit termination is not convergence. Optimization convergence concerns the final optimizer state; "
        "the validation-selected state may be earlier and need not be stationary. Terminal-residual means use available "
        "diagnostics among jointly successful pairs; unavailable counts are recorded in the audit.", "",
        f"| Model | Setting | Completed {short}/{long} | Optimizer converged {short}/{long} | "
        f"Selected state converged {short}/{long} | Mean terminal residual {short}/{long} | Termination counts {short} | Termination counts {long} |",
        "|---|---|---:|---:|---:|---:|---|---|"]
    for row in rows:
        a,b = row["base_counts"],row["extended_counts"]
        lines.append(f"| {row['model']} | {row['setting']} | {a['successful']}/{b['successful']} | "
            f"{a['optimization_converged']}/{b['optimization_converged']} | "
            f"{a['selected_converged']}/{b['selected_converged']} | "
            f"{_number(row['base_terminal_residual_mean'],4)}/{_number(row['extended_terminal_residual_mean'],4)} | "
            f"{json.dumps(a['termination_counts'],sort_keys=True)} | {json.dumps(b['termination_counts'],sort_keys=True)} |")
    lines += ["", "## Audit", "",
        f"Regenerated {audit['regenerated_unique_datasets']} unique datasets and checked {audit['verified_input_records']} "
        "result records against their training, validation, truth, and coefficient-error fingerprints. "
        f"Independently recomputed {audit['independently_recomputed_validation_scores']} selected validation MSEs "
        "from the saved coefficients and regenerated validation observations. "
        f"Observed implementation fingerprints: {len(audit['implementation_fingerprints'])}. "
        "A nonempty comparison must share one implementation fingerprint and one configuration after removing the iteration budget.", "",
        f"Compared {audit['compared_candidate_prefixes']} candidate validation prefixes exactly. "
        f"Prefix classifications: {json.dumps(audit['prefix_classifications'],sort_keys=True)}. "
        "Early convergence must reproduce at the same iteration. A failed candidate never becomes eligible through a partial coefficient.", "",
        f"Pairs losing at least one eligible candidate during continuation: {audit['pairs_losing_eligible_candidates']}. "
        "When the shorter-run winner remains eligible, the longer search must retain or improve its best validation loss.", "",
        audit["diagnostic_limit"], "", "Per-cell statuses, candidate eligibility changes, selected iterations, hashes, "
        "and paired aggregates are retained in [audit.json](audit.json).", ""]
    (output/"report.md").write_text("\n".join(lines))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-root",type=Path,default=DEFAULT_BASE_ROOT)
    parser.add_argument("--extended-root",type=Path,default=DEFAULT_EXTENDED_ROOT)
    parser.add_argument("--output-root",type=Path,default=DEFAULT_EXTENDED_ROOT/"iteration_summary")
    parser.add_argument("--model-ids",type=int,nargs="+",default=[0,1,2])
    parser.add_argument("--seed-ids",type=int,nargs="+",default=[0,1,2,3,4])
    parser.add_argument("--seed-file",type=Path,default=DEFAULT_SEED_FILE)
    args = parser.parse_args(argv)
    rows,audit = summarize(args.base_root,args.extended_root,model_ids=args.model_ids,
                          seed_ids=args.seed_ids,seed_file=args.seed_file)
    write_outputs(rows,audit,args.output_root)
    print(json.dumps(dict(expected_pairs=audit["expected_pairs"],paired_records=audit["paired_records"],
        successful_pairs=audit["successful_pairs"],output_root=str(args.output_root.resolve())),sort_keys=True))
    return 0


if __name__=="__main__":
    raise SystemExit(main())
